### ISSUE TITLE
Add this to an existing 3D game

### ISSUE THREAD

**Issue by havi05** [Yogoda/ZoneLoadingSystem#10]
Hi,

this system is really cool, but how do I add it to an existing 3d game?

I have the background loader loaded automatically.
Is that all or do I need to use BackgroundLoader.start(), etc. ?
Do I need to change a layer / layer name ?

Thank you,
Gamemap

P.S. It would also be nice if you could make a video of the installation for other users.  (but you do not have to)

**Comment by Yogoda** [comment]
Hello, thank you for your interest!

First, you need to split your world into zones, and save each zone as a separate *.tscn file.

Then create a new scene, name it world and save it, and replicate the node structure you see in the demo.

Follow the instructions "Configure the player" and "Add a new zone" in the Github to add your zones.

I know this is a bit complicated, I will try to think of a way to communicate it better :)

**Comment by havi05** [comment]
Ok, thanks a lot.

Do I need to use BackgroundLoader.start(), etc. ? (or just autoload ?)
~~Do I need to change a layer / layer name ? ( zone_triggers )
If yes, which number ?~~  **In the Demo it is the second layer.**

**Comment by Yogoda** [comment]
The BackgroundLoaded background thread is started automatically in the zone_loader script, so no need to start it.

**Comment by havi05** [comment]
I've tested it (and really like it), but can you change the layer (zone_triggers) to the last one so it probably won't collide with other previously defined layers? (for other users it could become a problem)

It is working wounderfull ;)  (I have only to rearrange my Player and World but that's ok for no loading screen) <3 <3 <3

**Comment by Yogoda** [comment]
This is a great suggestion, I updated the layer to use layer 16 instead, which should be free in most games.

Thanks!
