### ISSUE TITLE
Save function at unloading

### ISSUE THREAD

**Issue by havi05** [Yogoda/ZoneLoadingSystem#11]
Can you tell me where I can call a save function if the zone is unloading?

**Comment by Yogoda** [comment]
hello, the saving of zone is not implemented, but it looks like you save the zone yourself, good.

The unloading is normally done in zone_loader._remove_zone, when calling BackgroundLoader.request_unload(zone_id)
You can add your save code just before.

I realize there is a signal missing for zone unloading, sorry for that, I will fix it when I can.

**Comment by Yogoda** [comment]
Ok, I added a place to save the zone in world.gd ;) please update to the latest version.

**Comment by havi05** [comment]
Yes, I already have a save function.
Thank you

**Comment by Yogoda** [comment]
hello, there was an issue with signal for zone unloading that was triggering multiple time. I fixed it now and also added a new signal for zone loaded (for loading the save).

world.gd: _on_zone_loaded / _on_zone_about_to_unload

Please update to the latest version.

Also, using those functions you will load/save in the main thread, which might create small lag. If that is the case, you can try to save/load directly in the BackgroundLoader, using the background thread. However, it could create other issues, I did not test it.

Tell me how it goes.
