### ISSUE TITLE
Radius of zone loading

### ISSUE THREAD

**Issue by havi05** [Yogoda/ZoneLoadingSystem#12]
Hi,
is it possible to add a variable how many zones are loaded (radius)?
(If you have a better PC you can change it and have a greater view distance, else (maybe number 1) is like now)

**Comment by Yogoda** [comment]
Hello,

This system is for handcrafted zones, like for an FPS or 2D game.

What you are asking is for a chunk system like in Minecraft, this is a different system, and out of scope of this plugin.

So no, sorry.

**Comment by havi05** [comment]
I have thought about your loading system. 
Is it possible to change the player area size ingame to change the view distance?

**Comment by havi05** [comment]
I have test it (I have scaled the `ZoneTrigger` area). It is working in your demo also a `.scale.x` in script. 


Gamemap

**Comment by Yogoda** [comment]
You are right, it should work lol. It has not been designed to be used this way, but it should actually work, didn't think about this, contrats :)

**Comment by Yogoda** [comment]
Can you tell me what kind of game you are creating? Do you have zones of different sizes or terrain chunks like Minecraft?

**Comment by havi05** [comment]
I don't know the theme of my game yet (maybe airplane or open world RPG or both ;) ), but I thought to put related things in one zone (park with all objects, beach with all objects, etc.) So I have different zone sizes. 

Later I want to add a multiplayer. Is this compatible with the zone loading?    
 #8 (Change the current camera or is it possible that both players load and unload zones at the same time?)

**Comment by Yogoda** [comment]
Yes, it possible, as the zone loading is mainly a client-side feature.

However you will need to synchronize the zones (objects and NPC) across clients that have it loaded, this part could be tricky.

**Comment by havi05** [comment]
Ok I will try this later with a server.
Thank you for this great addon!

**Comment by Yogoda** [comment]
thank you for using it :)
