### ISSUE TITLE
Error after adding CollsionObject2D with CollisionShape2D to one of the Zones

### ISSUE THREAD

**Issue by Wrzlprnft** [Yogoda/ZoneLoadingSystem#6]
### Unexpected Behaviour:
Hiccups on loading and unloading zones as well as errors.
### Error Message:
```
E 0:00:02.430   set_shape_transform: Index p_index = 0 is out of bounds (shapes.size() = 0).
  <C++ Source>  servers/physics_2d/collision_object_2d_sw.cpp:78 @ set_shape_transform()
  <Stack Trace> zone_loader.gd:139 @ attach_zone()
```
followed by a variation of out of bounds errors, all from /servers/physics_2d/... in the Source Code and the same line in zone_loader
```
body_set_shape_disabled: Index p_shape_idx = 0 is out of bounds (body->get_shape_count() = 0).
[...]
body_set_shape_as_one_way_collision: Index p_shape_idx = 0 is out of bounds (body->get_shape_count() = 0).
[...]
body_set_shape_as_one_way_collision: Index p_shape_idx = 0 is out of bounds (body->get_shape_count() = 0).
[...]
```
### Steps to Reproduce:
In the Demo Project: Add e.g. a StaticBody2D with a CollsionShape2D (no matter which one) to Zone01

### Expected behaviour:
To work as with the 3D Demo Scene, where there are the 3D equivalent of static Bodies all over the place, loading and unloading smoothly

### Added Notes:
 On my private project there also seem to be some errors that seem to come from a TileMap and also seem to refer to missing data/bodies
```
 E 0:00:02.454   get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
  <C++ Source>  ./core/rid.h:150 @ get()
 E 0:00:02.458   body_set_mode: Condition "!body" is true.
  <C++ Source>  servers/physics_2d/physics_2d_server_sw.cpp:625 @ body_set_mode()
E 0:00:02.464   body_attach_object_instance_id: Condition "!body" is true.
  <C++ Source>  servers/physics_2d/physics_2d_server_sw.cpp:762 @ body_attach_object_instance_id()
```

### Tested Versions: 
ZoneLoadingSystem: Master as of e395b07 as well as release 1.3
Godot: 3.2.3
Windows10 2004

**Comment by Yogoda** [comment]
I'm able to reproduce the issue, I will look into it, thanks for the report.

Found this issue: https://github.com/godotengine/godot/issues/19465

**Comment by Yogoda** [comment]
Hello, I committed a fix, can you test if it fixes your issues?

For the hiccups, try disabling the debug log if enabled (on zone_loader.gd), it causes hiccups.

Thanks,
Joël

**Comment by Wrzlprnft** [comment]
I replaced the call in zone_loader.gd and left the rest of my personal project unchanged, and all the errors are gone (and with them the hiccups, which seemed related to the fact the the tilemap had many more collision-stuff going on and therefore there were hundreds of error messages)

ill close this issue now, since the unexpected behaviour has been adressed, which this issue was about. Thank you very very much for the quick response!

**Comment by Yogoda** [comment]
Awesome to know it fixed your issues :). I will create a new release with this fix.
