### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Clooloo** [Yogoda/ZoneLoadingSystem#8]
It is not an issue as it is out of scope but who better to help me than the genious who created this and thanks for such great project, but Im unable to set the zone loader for 2 players on different IP's(Computers), it does not finds the zoneloader, it does if I play both players on the same IP even thou it gets confused it only loads when 1 player moves but if I play on 2 different computers I get as far as the Lobby but I fail to find the Zoneloader node, I implemented the zone system to this Demo: https://github.com/godotengine/godot-demo-projects/tree/master/networking/multiplayer_bomber would you be able to suggest anything that may help a noob? :)

**Comment by Yogoda** [comment]
Hello! :)

It is a bit difficult to tell you what is wrong without the code, could be anything. Can you send me the files? I'll take a look.

**Comment by Clooloo** [comment]
Thanks a lot for your response I put my code here, https://github.com/Clooloo/zoneloadingmultiplayertest  I disabled the bombs because they are also been registered on the zones and they freak out but I don't care about that least not as of now hehehe, trying to make it work with the 2 players :) just as extra info, testing with different IP's gives different results.

**Comment by Yogoda** [comment]
I see, you set the reference to zone_loader in gamestate.gd, gamestate is an autoload, so it will be created at the root of the tree, so it won't find a child named "zone_loader". You need to set it in world, like in my demo.

Also, keep in mind there are 2 camera, one in each player, so you need to set the active camera in the player the user is moving:

	if is_network_master():
		$Camera2D.current = true
	else:
		$Camera2D.current = false

It seems you are trying to do something very complicated (multiplayer + async loading), you should start with simpler projects to have a better understanding of Godot, and once you have solid bases then you can do multiplayer ;)

Hope this helps.
Joël

**Comment by Clooloo** [comment]
Swwweeet Thank you very much let me look into this :)
